export const COUNTRY_CODES = [
  // Afrique
  { code: '+213', flag: '🇩🇿', name: 'Algérie' },
  { code: '+216', flag: '🇹🇳', name: 'Tunisie' },
  { code: '+212', flag: '🇲🇦', name: 'Maroc' },
  { code: '+20', flag: '🇪🇬', name: 'Égypte' },
  { code: '+221', flag: '🇸🇳', name: 'Sénégal' },
  { code: '+225', flag: '🇨🇮', name: "Côte d'Ivoire" },

  // Amérique
  { code: '+1', flag: '🇨🇦', name: 'Canada' },
  { code: '+1', flag: '🇺🇸', name: 'États-Unis' },

  // Europe
  { code: '+355', flag: '🇦🇱', name: 'Albanie' },
  { code: '+376', flag: '🇦🇩', name: 'Andorre' },
  { code: '+43', flag: '🇦🇹', name: 'Autriche' },
  { code: '+32', flag: '🇧🇪', name: 'Belgique' },
  { code: '+375', flag: '🇧🇾', name: 'Biélorussie' },
  { code: '+387', flag: '🇧🇦', name: 'Bosnie-Herzégovine' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgarie' },
  { code: '+385', flag: '🇭🇷', name: 'Croatie' },
  { code: '+357', flag: '🇨🇾', name: 'Chypre' },
  { code: '+420', flag: '🇨🇿', name: 'République tchèque' },
  { code: '+45', flag: '🇩🇰', name: 'Danemark' },
  { code: '+372', flag: '🇪🇪', name: 'Estonie' },
  { code: '+358', flag: '🇫🇮', name: 'Finlande' },
  { code: '+33', flag: '🇫🇷', name: 'France' },
  { code: '+49', flag: '🇩🇪', name: 'Allemagne' },
  { code: '+30', flag: '🇬🇷', name: 'Grèce' },
  { code: '+36', flag: '🇭🇺', name: 'Hongrie' },
  { code: '+354', flag: '🇮🇸', name: 'Islande' },
  { code: '+353', flag: '🇮🇪', name: 'Irlande' },
  { code: '+39', flag: '🇮🇹', name: 'Italie' },
  { code: '+383', flag: '🇽🇰', name: 'Kosovo' },
  { code: '+371', flag: '🇱🇻', name: 'Lettonie' },
  { code: '+423', flag: '🇱🇮', name: 'Liechtenstein' },
  { code: '+370', flag: '🇱🇹', name: 'Lituanie' },
  { code: '+352', flag: '🇱🇺', name: 'Luxembourg' },
  { code: '+356', flag: '🇲🇹', name: 'Malte' },
  { code: '+373', flag: '🇲🇩', name: 'Moldavie' },
  { code: '+377', flag: '🇲🇨', name: 'Monaco' },
  { code: '+382', flag: '🇲🇪', name: 'Monténégro' },
  { code: '+31', flag: '🇳🇱', name: 'Pays-Bas' },
  { code: '+389', flag: '🇲🇰', name: 'Macédoine du Nord' },
  { code: '+47', flag: '🇳🇴', name: 'Norvège' },
  { code: '+48', flag: '🇵🇱', name: 'Pologne' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal' },
  { code: '+40', flag: '🇷🇴', name: 'Roumanie' },
  { code: '+7', flag: '🇷🇺', name: 'Russie' },
  { code: '+378', flag: '🇸🇲', name: 'Saint-Marin' },
  { code: '+381', flag: '🇷🇸', name: 'Serbie' },
  { code: '+421', flag: '🇸🇰', name: 'Slovaquie' },
  { code: '+386', flag: '🇸🇮', name: 'Slovénie' },
  { code: '+34', flag: '🇪🇸', name: 'Espagne' },
  { code: '+46', flag: '🇸🇪', name: 'Suède' },
  { code: '+41', flag: '🇨🇭', name: 'Suisse' },
  { code: '+90', flag: '🇹🇷', name: 'Turquie' },
  { code: '+380', flag: '🇺🇦', name: 'Ukraine' },
  { code: '+44', flag: '🇬🇧', name: 'Royaume-Uni' },
  { code: '+379', flag: '🇻🇦', name: 'Vatican' },

  // Moyen-Orient
  { code: '+966', flag: '🇸🇦', name: 'Arabie saoudite' },
  { code: '+971', flag: '🇦🇪', name: 'Émirats arabes unis' },
];

export const STATUS_STYLE = {
  en_attente: { cls: 'badge-yellow', label: '⏳ En attente' },
  approuvée:  { cls: 'badge-green',  label: '✅ Approuvée' },
  en_cours:   { cls: 'badge-blue',   label: '🔄 En cours' },
  terminée:   { cls: 'badge-gray',   label: '🏁 Terminée' },
  annulée:    { cls: 'badge-red',    label: '🚫 Annulée' },
  refusée:    { cls: 'badge-red',    label: '❌ Refusée' },
};

export const inputSt = (err) => ({
  width: '100%',
  padding: '11px 14px',
  border: `1.5px solid ${err ? '#ef4444' : '#e5e7eb'}`,
  borderRadius: 10,
  fontSize: 15,
  outline: 'none',
  boxSizing: 'border-box',
  background: err ? '#fff5f5' : '#fff',
  transition: 'border-color 0.15s',
});
